networks:
  kitaischool_network:
    driver: bridge

volumes:
  kitaischool_pgdata:
  kitaischool_media:

services:
  kitaischool_database:
    env_file:
      - kitaischool.env
    image: postgres:latest
    ports:
      - "${PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_HOST: localhost
    networks:
      - kitaischool_network
    volumes:
      - kitaischool_pgdata:/var/lib/postgresql/data
    restart: always

  kitaischool_django:
    env_file:
      - kitaischool.env
    build: .
    ports:
      - "5001:5000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: kitaischool_database
      PORT: 5432
      PYTHONUNBUFFERED: 1
    entrypoint: bash -c  "python manage.py collectstatic --noinput &&  python manage.py makemigrations && python manage.py migrate &&  gunicorn --bind 0.0.0.0:5000 dls.wsgi:application";
    depends_on:
      - kitaischool_database
    networks:
      - kitaischool_network
    volumes:
      - kitaischool_media:/src/media
    restart: always

  kitaischool_redis:
    image: redis:latest
    restart: always
    networks:
      - kitaischool_network

  kitaischool_celery:
    env_file:
      - kitaischool.env
    build: .
    depends_on:
      - kitaischool_redis
      - kitaischool_django
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    command: celery -A dls worker -l info
    networks:
      - kitaischool_network
  kitaischool_bot:
    env_file:
      - kitaischool.env
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: kitaischool_database
      PORT: 5432
      PYTHONUNBUFFERED: 1
    entrypoint: bash -c  "python manage.py runbot";
    depends_on:
      - kitaischool_celery
    networks:
      - kitaischool_network
    restart: always