version: '3.9'

networks:
    datenetwork:
        driver: bridge

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - '8080:80'
    networks:
      - datenetwork
    depends_on:
      - site
    volumes:
      - ./site/static:/src/static
    restart: always
  dateindb:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_HOST: localhost
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - datenetwork
    restart: always
  site:
    build: site
    environment:
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    entrypoint: bash -c  "python manage.py collectstatic --noinput &&  python manage.py makemigrations && python manage.py migrate &&  gunicorn --bind 0.0.0.0:5000 datein.wsgi:application";
    depends_on:
      - dateindb
    networks:
      - datenetwork
    restart: always
  redis:
    image: redis:latest
    restart: always
    networks:
      - datenetwork
  celery:
    build: site
    depends_on:
      - redis
      - site
    command: celery -A datein worker -l info
    networks:
      - datenetwork
  celerybeat:
    build: site
    depends_on:
      - redis
      - site
    command: celery -A datein beat -l info
    networks:
      - datenetwork
  telegram:
    build: tg_bot
    depends_on:
      - site
      - dateindb
    command: python /src/main.py
    environment:
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TG_TOKEN: ${TG_TOKEN}
      VK_TOKEN: ${VK_TOKEN}
      API_URL: ${API_URL}
      API_TOKEN: ${API_TOKEN}
      VK_GROUP_ID: ${VK_GROUP_ID}
      TG_WEBHOOK_MODE: ${TG_WEBHOOK_MODE}
    networks:
      - datenetwork
  vk:
    build: vk_bot
    depends_on:
      - site
      - dateindb
    command: python /src/main.py
    environment:
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      VK_TOKEN: ${VK_TOKEN}
      VK_SERV_TOKEN: ${VK_SERV_TOKEN}
      API_URL: ${API_URL}
      API_TOKEN: ${API_TOKEN}
      VK_GROUP_ID: ${VK_GROUP_ID}
      VK_CALLBACK_MODE: ${VK_CALLBACK_MODE}
      VK_CONFIRMATION_KEY: ${VK_CONFIRMATION_KEY}
      VK_SECRET_KEY: ${VK_SECRET_KEY}
    networks:
      - datenetwork